name: CD

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Install dependencies
              run: go mod download

            - name: Build project
              shell: bash
              run: |
                  mkdir build && cd build
                  for cmd in ../cmd/*/; do
                    go build ${cmd}
                  done

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ matrix.os }}
                  path: build/**/*

    release:
        name: Create release
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4

            - name: Archive build artifacts
              run: |
                  zip -j dist/app-${APP_PLATFORM}.zip ./build-windows-latest/
                  tar -czf dist/app-${APP_PLATFORM}.tar.gz -C . ./build-ubuntu-latest/

            - name: Upload release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./dist/**/*
