name: CD

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Install dependencies
              run: go mod download

            - name: Build project
              run: |
                  mkdir build && cd build
                  go build ../app/

            - name: Get arch-os string
              shell: bash
              run: |
                  APP_ARCH=$(go env GOARCH)
                  APP_OS=$(go env GOOS)
                  APP_PLATFORM=${APP_ARCH}-${APP_OS}
                  echo "APP_PLATFORM=${APP_PLATFORM}" >> $GITHUB_ENV
                  echo "Target platform is ${APP_PLATFORM}"

            - name: Archive build artifacts
              if: matrix.os == 'ubuntu-latest'
              run: |
                  mkdir dist
                  if [ "$RUNNER_OS" == "Windows" ]; then
                    Compress-Archive -Path ./build/* -Destination dist/app-${APP_PLATFORM}.zip
                  else
                    tar -czf dist/app-${APP_PLATFORM}.tar.gz -C . build
                  fi

            - name: Upload archive
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ matrix.os }}
                  path: dist/**/*

    release:
        name: Create release
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: Upload release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./artifacts/**/*
