name: CI

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v3
              with:
                  go-version-file: go.mod

            - name: Install dependencies
              run: go mod tidy

            - name: Run tests
              run: go test -v -coverprofile=coverage.out ./...

            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
