name: Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        name: Run Tests and Update Coverage
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test -v -coverprofile=coverage.out ./...

            - name: Update coverage report
              uses: coverallsapp/github-action@v2
              with:
                  file: coverage.out
                  format: golang
